# Generated by Django 5.2.4 on 2025-08-18 23:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('feature_key', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_beam_sessions', models.IntegerField(default=0)),
                ('max_connected_devices', models.IntegerField(default=0)),
                ('max_file_size_mb', models.IntegerField(default=0)),
                ('session_history_days', models.IntegerField(default=0)),
                ('has_rich_editor', models.BooleanField(default=False)),
                ('has_file_uploads', models.BooleanField(default=False)),
                ('has_advanced_permissions', models.BooleanField(default=False)),
                ('has_api_access', models.BooleanField(default=False)),
                ('has_sso_integration', models.BooleanField(default=False)),
                ('has_priority_support', models.BooleanField(default=False)),
                ('has_custom_branding', models.BooleanField(default=False)),
                ('has_analytics', models.BooleanField(default=False)),
                ('has_team_collaboration', models.BooleanField(default=False)),
                ('support_level', models.CharField(choices=[('community', 'Community'), ('email', 'Email'), ('live_chat', 'Live Chat'), ('sla', 'SLA')], default='community', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price_monthly'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='PlanPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price_yearly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price_yearly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(blank=True)),
                ('effective_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='plans.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('trial', 'Trial')], default='active', max_length=20)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('trial_expires_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('current_beam_sessions', models.IntegerField(default=0)),
                ('total_file_uploads', models.IntegerField(default=0)),
                ('total_data_transferred_mb', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beam_sessions_created', models.IntegerField(default=0)),
                ('files_uploaded', models.IntegerField(default=0)),
                ('total_file_size_mb', models.IntegerField(default=0)),
                ('notes_created', models.IntegerField(default=0)),
                ('api_calls_made', models.IntegerField(default=0)),
                ('total_beam_sessions', models.IntegerField(default=0)),
                ('total_files_uploaded', models.IntegerField(default=0)),
                ('total_notes_created', models.IntegerField(default=0)),
                ('total_api_calls', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='plans.userplan')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='one_active_plan_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='userplan',
            unique_together={('user', 'status')},
        ),
    ]
