# Generated by Django 5.2.4 on 2025-09-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_audio_transcription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_cloud_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_cross_device_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_ocr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_presentation_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_share_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_templates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_version_history',
            field=models.BooleanField(default=False),
        ),
    ]
