# Generated by Django 5.2.4 on 2025-08-04 21:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, max_length=5000, null=True)),
                ('json_content', models.JSONField(blank=True, null=True)),
                ('note_type', models.CharField(choices=[('text', 'Text'), ('lexi_note', 'Lexi Note'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
