# Generated by Django 5.2.4 on 2025-08-05 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beam', '0002_beam_created_at'),
        ('note', '0002_note_created_at_note_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='beam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beam.beam'),
        ),
    ]
