# Generated by Django 5.2.4 on 2025-07-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beam_id', models.CharField(max_length=255, unique=True)),
                ('beam_key', models.TextField()),
            ],
        ),
    ]
